name: releasing

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Avoid running against a shallow clone

      - name: Force fetch upstream tags
        run: git fetch --force --tags

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
            go-version: 1.22
            check-latest: true

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}